
CREATE TABLE IF NOT EXISTS user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(25) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    address VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_type VARCHAR(15) NOT NULL,
    event_date VARCHAR(15) NOT NULL,
    venue VARCHAR(25) NOT NULL,
    guests INT NOT NULL,
    name VARCHAR(25) NOT NULL,
    email VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS contact (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    number VARCHAR(10) NOT NULL,
    email VARCHAR(25) NOT NULL,
    message VARCHAR(255) NOT NULL
);
